create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  content text not null,
  rating integer default 5,
  avatar_url text,
  video_url text,
  is_published boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text,
  preferred_date date,
  message text,
  admin_email text default 'admin@example.com',
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.feedbacks
add column if not exists video_url text;

alter table public.appointments
add column if not exists is_read boolean default false;

alter table public.feedbacks enable row level security;
alter table public.appointments enable row level security;

grant usage on schema public to public;
grant insert on public.feedbacks to public;
grant select on public.feedbacks to public;
grant insert on public.appointments to public;
grant select, update on public.appointments to authenticated;
grant update on public.feedbacks to authenticated;
grant usage, select on all sequences in schema public to public;

drop policy if exists "Anyone can submit feedback" on public.feedbacks;
create policy "Anyone can submit feedback"
on public.feedbacks
for insert
to public
with check (true);

drop policy if exists "Anyone can book appointment" on public.appointments;
create policy "Anyone can book appointment"
on public.appointments
for insert
to public
with check (true);

drop policy if exists "Anyone can view approved feedback" on public.feedbacks;
create policy "Anyone can view approved feedback"
on public.feedbacks
for select
to public
using (is_published = true);

drop policy if exists "Admin can manage all feedbacks" on public.feedbacks;
create policy "Admin can manage all feedbacks"
on public.feedbacks
for all
to authenticated
using (auth.jwt() ->> 'email' = 'admin@example.com')
with check (auth.jwt() ->> 'email' = 'admin@example.com');

drop policy if exists "Admin can manage all appointments" on public.appointments;
create policy "Admin can manage all appointments"
on public.appointments
for all
to authenticated
using (auth.jwt() ->> 'email' = 'admin@example.com')
with check (auth.jwt() ->> 'email' = 'admin@example.com');

-- Create storage bucket for feedback videos
insert into storage.buckets (id, name, public)
values ('feedback-videos', 'feedback-videos', true)
on conflict (id) do nothing;

-- Enable RLS on storage.objects if it is not enabled
alter table storage.objects enable row level security;

-- Storage Policies for anyone to upload feedback videos
drop policy if exists "Anyone can upload feedback videos" on storage.objects;
create policy "Anyone can upload feedback videos"
on storage.objects for insert to public
with check (bucket_id = 'feedback-videos');

-- Storage Policies for anyone to view feedback videos
drop policy if exists "Anyone can view feedback videos" on storage.objects;
create policy "Anyone can view feedback videos"
on storage.objects for select to public
using (bucket_id = 'feedback-videos');
